### ISSUE TITLE
updates to the app - figures and titles

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/nhanesShinyBP#14]
Should we remove the horizontal gridlines?
Add a line for the y-axis similar to the x-axis.
Can we add tick marks on the y-axis?
I plan to add a new variable to the data set:
Self-reported antihypertensive medication use confirmed by pill bottle review

For the title – can this be centered across the graph?  Also, can we spell out names?  Below are label changes.
Blood pressure control (JNC7 defn) - Blood pressure control (SBP < 140 mm Hg and DBP < 90 mm Hg)
Blood pressure control (ACC/AHA 2017 defn) - Blood pressure control (SBP < 130 mm Hg and DBP < 80 mm Hg)
Hypertension (JNC7 defn) – Hypertension (JNC7 guideline definition) 
Hypertension (ACC/AHA defn) – Hypertension (2017 ACC/AHA blood pressure guideline definition) 
 Resistant hypertension (JNC7 defn) – Prevalence of resistant hypertension - JNC7 guideline definition
Resistant hypertension (ACC/AHA 2017 defn) – Prevalence of resistant hypertension – 2017 ACC/AHA BP guideline definition
Antihypertensive medication use – Self-reported antihypertensive medication use

**Comment by bcjaeger** [comment]
For the labels, may I modify the updates for resistant hypertension?

- Resistant hypertension (JNC7 defn) – ~~Prevalence of~~ Resistant hypertension - JNC7 guideline definition
- Resistant hypertension (ACC/AHA 2017 defn) – ~~Prevalence of~~ Resistant hypertension – 2017 ACC/AHA BP guideline definition

I'd like to remove the 'prevalence' component from the name because the app asks users to select a statistic to compute, and currently for binary variables the options are 'prevalence' and 'count'. Having prevalence in the title of the output would be incorrect if the user only selected 'count' as a statistic to compute.

All other labels have been updated!

**Comment by bcjaeger** [comment]
The plot aesthetics have been updated!
- no more grid lines
- tick marks on y-axis
- visible y-axis (similar to x-axis)
- centered title

To get these updates, run: 

```
remotes::install_github('jhs-hwg/nhanesShinyBP')
# select no updates for dependent packages

library(nhanesShinyBP)

app_run()

```

**Comment by bcjaeger** [comment]
Aesthetics are looking good. Closing this issue for now.
