### ISSUE TITLE
Title....

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/nhanesShinyBP#36]
I was traveling this morning and missed the conversation. I would suggest removing NHANES from the title of the app since we are not a sanctioned NHANES app.  I wonder if we could have something that would (1) attract users and (2) be picked up by google.  US cardiovascular statistics.  Are we limited by a character count?  Please propose something better.

**Comment by bcjaeger** [comment]
> I would suggest removing NHANES from the title of the app since we are not a sanctioned NHANES app

That is a great point. 

> Are we limited by a character count?

We can make the name as long as we want but should keep it all in one word (in case we want to put the R package on CRAN at some point in the future - CRAN does not allow packages with spaces in their names).

> Please propose something better.

What do you think of 

- package name: `cardioStats`  or `cardioTrends` or `US.CVD.Trends` or `US.CVD.Stats`
- description: Analyze trends in and summaries of cardiovascular outcomes among adults living in the United States of America  

I think search engines will check the description and key words when they search. The name will most likely only be looked at by people. I tend to try and make the name minimal because I feel like minimal names are easier to remember, but I don't know if everyone else feels that way.

**Comment by bcjaeger** [comment]
Should we stick with the idea of the package being about CVD even though we plan on adding diabetes outcomes?

**Comment by bcjaeger** [comment]
Giving this some thought, I am leaning in the direction of 

- package name: `cardioStats.USA`
- Description: Analyze cardiometabolic outcomes among adults living in the United States of America using data from the National Health and Nutrition Examination Survey.

@ligongus and @pmuntner, let me know by 9/23 if you'd prefer a different name. It is easy to change the description whenever we want but it is time-consuming to change the package name, so I'd like to change it just once.

**Comment by bcjaeger** [comment]
`cardioStats.USA` is the winner!

**Comment by ligongus** [comment]
I think it's a good name.

**Comment by pmuntner** [comment]
I like US.CVD.Stats


    On Saturday, August 20, 2022 at 03:25:26 PM CDT, Byron ***@***.***> wrote:  
 
 



I would suggest removing NHANES from the title of the app since we are not a sanctioned NHANES app


That is a great point.


Are we limited by a character count?


We can make the name as long as we want but should keep it all in one word (in case we want to put the R package on CRAN at some point in the future - CRAN does not allow packages with spaces in their names).


Please propose something better.


What do you think of
   
   - package name: cardioStats or cardioTrends or US.CVD.Trends or US.CVD.Stats
   - description: Analyze trends in and summaries of cardiovascular outcomes among adults living in the United States of America

I think search engines will check the description and key words when they search. The name will most likely only be looked at by people. I tend to try and make the name minimal because I feel like minimal names are easier to remember, but I don't know if everyone else feels that way.
